package com.example.demo.dao.entity;

import java.util.Date;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.ID
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.USER_NAME
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.PASSWORD
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.USER_NO
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    private String userNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.PHONE_NO
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    private String phoneNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.EMAIL
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.USER_TYPE
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    private Integer userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.OTHER_INFO1
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    private String otherInfo1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.OTHER_INFO2
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    private String otherInfo2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.OTHER_INFO3
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    private String otherInfo3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.OTHER_INFO4
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    private String otherInfo4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.OTHER_INFO5
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    private String otherInfo5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.CREATE_DATE
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.CREATE_UID
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    private String createUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.UPDATE_DATE
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.UPDATE_UID
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    private String updateUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.DEL_FLAG
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_INFO.USER_ROLES_IN_SYS
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    private String userRolesInSys;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.ID
     *
     * @return the value of USER_INFO.ID
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.ID
     *
     * @param id the value for USER_INFO.ID
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.USER_NAME
     *
     * @return the value of USER_INFO.USER_NAME
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.USER_NAME
     *
     * @param userName the value for USER_INFO.USER_NAME
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.PASSWORD
     *
     * @return the value of USER_INFO.PASSWORD
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.PASSWORD
     *
     * @param password the value for USER_INFO.PASSWORD
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.USER_NO
     *
     * @return the value of USER_INFO.USER_NO
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.USER_NO
     *
     * @param userNo the value for USER_INFO.USER_NO
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.PHONE_NO
     *
     * @return the value of USER_INFO.PHONE_NO
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.PHONE_NO
     *
     * @param phoneNo the value for USER_INFO.PHONE_NO
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.EMAIL
     *
     * @return the value of USER_INFO.EMAIL
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.EMAIL
     *
     * @param email the value for USER_INFO.EMAIL
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.USER_TYPE
     *
     * @return the value of USER_INFO.USER_TYPE
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.USER_TYPE
     *
     * @param userType the value for USER_INFO.USER_TYPE
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.OTHER_INFO1
     *
     * @return the value of USER_INFO.OTHER_INFO1
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public String getOtherInfo1() {
        return otherInfo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.OTHER_INFO1
     *
     * @param otherInfo1 the value for USER_INFO.OTHER_INFO1
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public void setOtherInfo1(String otherInfo1) {
        this.otherInfo1 = otherInfo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.OTHER_INFO2
     *
     * @return the value of USER_INFO.OTHER_INFO2
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public String getOtherInfo2() {
        return otherInfo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.OTHER_INFO2
     *
     * @param otherInfo2 the value for USER_INFO.OTHER_INFO2
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public void setOtherInfo2(String otherInfo2) {
        this.otherInfo2 = otherInfo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.OTHER_INFO3
     *
     * @return the value of USER_INFO.OTHER_INFO3
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public String getOtherInfo3() {
        return otherInfo3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.OTHER_INFO3
     *
     * @param otherInfo3 the value for USER_INFO.OTHER_INFO3
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public void setOtherInfo3(String otherInfo3) {
        this.otherInfo3 = otherInfo3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.OTHER_INFO4
     *
     * @return the value of USER_INFO.OTHER_INFO4
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public String getOtherInfo4() {
        return otherInfo4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.OTHER_INFO4
     *
     * @param otherInfo4 the value for USER_INFO.OTHER_INFO4
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public void setOtherInfo4(String otherInfo4) {
        this.otherInfo4 = otherInfo4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.OTHER_INFO5
     *
     * @return the value of USER_INFO.OTHER_INFO5
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public String getOtherInfo5() {
        return otherInfo5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.OTHER_INFO5
     *
     * @param otherInfo5 the value for USER_INFO.OTHER_INFO5
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public void setOtherInfo5(String otherInfo5) {
        this.otherInfo5 = otherInfo5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.CREATE_DATE
     *
     * @return the value of USER_INFO.CREATE_DATE
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.CREATE_DATE
     *
     * @param createDate the value for USER_INFO.CREATE_DATE
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.CREATE_UID
     *
     * @return the value of USER_INFO.CREATE_UID
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public String getCreateUid() {
        return createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.CREATE_UID
     *
     * @param createUid the value for USER_INFO.CREATE_UID
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public void setCreateUid(String createUid) {
        this.createUid = createUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.UPDATE_DATE
     *
     * @return the value of USER_INFO.UPDATE_DATE
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.UPDATE_DATE
     *
     * @param updateDate the value for USER_INFO.UPDATE_DATE
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.UPDATE_UID
     *
     * @return the value of USER_INFO.UPDATE_UID
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public String getUpdateUid() {
        return updateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.UPDATE_UID
     *
     * @param updateUid the value for USER_INFO.UPDATE_UID
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public void setUpdateUid(String updateUid) {
        this.updateUid = updateUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.DEL_FLAG
     *
     * @return the value of USER_INFO.DEL_FLAG
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public Integer getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.DEL_FLAG
     *
     * @param delFlag the value for USER_INFO.DEL_FLAG
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_INFO.USER_ROLES_IN_SYS
     *
     * @return the value of USER_INFO.USER_ROLES_IN_SYS
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public String getUserRolesInSys() {
        return userRolesInSys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_INFO.USER_ROLES_IN_SYS
     *
     * @param userRolesInSys the value for USER_INFO.USER_ROLES_IN_SYS
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public void setUserRolesInSys(String userRolesInSys) {
        this.userRolesInSys = userRolesInSys;
    }
}