package com.example.demo.dao.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table USER_INFO
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table USER_INFO
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table USER_INFO
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public UserInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_INFO
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table USER_INFO
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("USER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("USER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("USER_NAME =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("USER_NAME <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("USER_NAME >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("USER_NAME >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("USER_NAME <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("USER_NAME <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("USER_NAME like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("USER_NAME not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("USER_NAME in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("USER_NAME not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("USER_NAME between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("USER_NAME not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("PASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("PASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("PASSWORD =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("PASSWORD <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("PASSWORD >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("PASSWORD >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("PASSWORD <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("PASSWORD <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("PASSWORD like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("PASSWORD not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("PASSWORD in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("PASSWORD not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("PASSWORD between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("PASSWORD not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andUserNoIsNull() {
            addCriterion("USER_NO is null");
            return (Criteria) this;
        }

        public Criteria andUserNoIsNotNull() {
            addCriterion("USER_NO is not null");
            return (Criteria) this;
        }

        public Criteria andUserNoEqualTo(String value) {
            addCriterion("USER_NO =", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoNotEqualTo(String value) {
            addCriterion("USER_NO <>", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoGreaterThan(String value) {
            addCriterion("USER_NO >", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoGreaterThanOrEqualTo(String value) {
            addCriterion("USER_NO >=", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoLessThan(String value) {
            addCriterion("USER_NO <", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoLessThanOrEqualTo(String value) {
            addCriterion("USER_NO <=", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoLike(String value) {
            addCriterion("USER_NO like", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoNotLike(String value) {
            addCriterion("USER_NO not like", value, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoIn(List<String> values) {
            addCriterion("USER_NO in", values, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoNotIn(List<String> values) {
            addCriterion("USER_NO not in", values, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoBetween(String value1, String value2) {
            addCriterion("USER_NO between", value1, value2, "userNo");
            return (Criteria) this;
        }

        public Criteria andUserNoNotBetween(String value1, String value2) {
            addCriterion("USER_NO not between", value1, value2, "userNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoIsNull() {
            addCriterion("PHONE_NO is null");
            return (Criteria) this;
        }

        public Criteria andPhoneNoIsNotNull() {
            addCriterion("PHONE_NO is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneNoEqualTo(String value) {
            addCriterion("PHONE_NO =", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoNotEqualTo(String value) {
            addCriterion("PHONE_NO <>", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoGreaterThan(String value) {
            addCriterion("PHONE_NO >", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoGreaterThanOrEqualTo(String value) {
            addCriterion("PHONE_NO >=", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoLessThan(String value) {
            addCriterion("PHONE_NO <", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoLessThanOrEqualTo(String value) {
            addCriterion("PHONE_NO <=", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoLike(String value) {
            addCriterion("PHONE_NO like", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoNotLike(String value) {
            addCriterion("PHONE_NO not like", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoIn(List<String> values) {
            addCriterion("PHONE_NO in", values, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoNotIn(List<String> values) {
            addCriterion("PHONE_NO not in", values, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoBetween(String value1, String value2) {
            addCriterion("PHONE_NO between", value1, value2, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoNotBetween(String value1, String value2) {
            addCriterion("PHONE_NO not between", value1, value2, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("EMAIL =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("EMAIL <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("EMAIL >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("EMAIL <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("EMAIL <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("EMAIL like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("EMAIL not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("EMAIL in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("EMAIL not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("EMAIL between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("EMAIL not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andUserTypeIsNull() {
            addCriterion("USER_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andUserTypeIsNotNull() {
            addCriterion("USER_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andUserTypeEqualTo(Integer value) {
            addCriterion("USER_TYPE =", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotEqualTo(Integer value) {
            addCriterion("USER_TYPE <>", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeGreaterThan(Integer value) {
            addCriterion("USER_TYPE >", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("USER_TYPE >=", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLessThan(Integer value) {
            addCriterion("USER_TYPE <", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLessThanOrEqualTo(Integer value) {
            addCriterion("USER_TYPE <=", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeIn(List<Integer> values) {
            addCriterion("USER_TYPE in", values, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotIn(List<Integer> values) {
            addCriterion("USER_TYPE not in", values, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeBetween(Integer value1, Integer value2) {
            addCriterion("USER_TYPE between", value1, value2, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("USER_TYPE not between", value1, value2, "userType");
            return (Criteria) this;
        }

        public Criteria andOtherInfo1IsNull() {
            addCriterion("OTHER_INFO1 is null");
            return (Criteria) this;
        }

        public Criteria andOtherInfo1IsNotNull() {
            addCriterion("OTHER_INFO1 is not null");
            return (Criteria) this;
        }

        public Criteria andOtherInfo1EqualTo(String value) {
            addCriterion("OTHER_INFO1 =", value, "otherInfo1");
            return (Criteria) this;
        }

        public Criteria andOtherInfo1NotEqualTo(String value) {
            addCriterion("OTHER_INFO1 <>", value, "otherInfo1");
            return (Criteria) this;
        }

        public Criteria andOtherInfo1GreaterThan(String value) {
            addCriterion("OTHER_INFO1 >", value, "otherInfo1");
            return (Criteria) this;
        }

        public Criteria andOtherInfo1GreaterThanOrEqualTo(String value) {
            addCriterion("OTHER_INFO1 >=", value, "otherInfo1");
            return (Criteria) this;
        }

        public Criteria andOtherInfo1LessThan(String value) {
            addCriterion("OTHER_INFO1 <", value, "otherInfo1");
            return (Criteria) this;
        }

        public Criteria andOtherInfo1LessThanOrEqualTo(String value) {
            addCriterion("OTHER_INFO1 <=", value, "otherInfo1");
            return (Criteria) this;
        }

        public Criteria andOtherInfo1Like(String value) {
            addCriterion("OTHER_INFO1 like", value, "otherInfo1");
            return (Criteria) this;
        }

        public Criteria andOtherInfo1NotLike(String value) {
            addCriterion("OTHER_INFO1 not like", value, "otherInfo1");
            return (Criteria) this;
        }

        public Criteria andOtherInfo1In(List<String> values) {
            addCriterion("OTHER_INFO1 in", values, "otherInfo1");
            return (Criteria) this;
        }

        public Criteria andOtherInfo1NotIn(List<String> values) {
            addCriterion("OTHER_INFO1 not in", values, "otherInfo1");
            return (Criteria) this;
        }

        public Criteria andOtherInfo1Between(String value1, String value2) {
            addCriterion("OTHER_INFO1 between", value1, value2, "otherInfo1");
            return (Criteria) this;
        }

        public Criteria andOtherInfo1NotBetween(String value1, String value2) {
            addCriterion("OTHER_INFO1 not between", value1, value2, "otherInfo1");
            return (Criteria) this;
        }

        public Criteria andOtherInfo2IsNull() {
            addCriterion("OTHER_INFO2 is null");
            return (Criteria) this;
        }

        public Criteria andOtherInfo2IsNotNull() {
            addCriterion("OTHER_INFO2 is not null");
            return (Criteria) this;
        }

        public Criteria andOtherInfo2EqualTo(String value) {
            addCriterion("OTHER_INFO2 =", value, "otherInfo2");
            return (Criteria) this;
        }

        public Criteria andOtherInfo2NotEqualTo(String value) {
            addCriterion("OTHER_INFO2 <>", value, "otherInfo2");
            return (Criteria) this;
        }

        public Criteria andOtherInfo2GreaterThan(String value) {
            addCriterion("OTHER_INFO2 >", value, "otherInfo2");
            return (Criteria) this;
        }

        public Criteria andOtherInfo2GreaterThanOrEqualTo(String value) {
            addCriterion("OTHER_INFO2 >=", value, "otherInfo2");
            return (Criteria) this;
        }

        public Criteria andOtherInfo2LessThan(String value) {
            addCriterion("OTHER_INFO2 <", value, "otherInfo2");
            return (Criteria) this;
        }

        public Criteria andOtherInfo2LessThanOrEqualTo(String value) {
            addCriterion("OTHER_INFO2 <=", value, "otherInfo2");
            return (Criteria) this;
        }

        public Criteria andOtherInfo2Like(String value) {
            addCriterion("OTHER_INFO2 like", value, "otherInfo2");
            return (Criteria) this;
        }

        public Criteria andOtherInfo2NotLike(String value) {
            addCriterion("OTHER_INFO2 not like", value, "otherInfo2");
            return (Criteria) this;
        }

        public Criteria andOtherInfo2In(List<String> values) {
            addCriterion("OTHER_INFO2 in", values, "otherInfo2");
            return (Criteria) this;
        }

        public Criteria andOtherInfo2NotIn(List<String> values) {
            addCriterion("OTHER_INFO2 not in", values, "otherInfo2");
            return (Criteria) this;
        }

        public Criteria andOtherInfo2Between(String value1, String value2) {
            addCriterion("OTHER_INFO2 between", value1, value2, "otherInfo2");
            return (Criteria) this;
        }

        public Criteria andOtherInfo2NotBetween(String value1, String value2) {
            addCriterion("OTHER_INFO2 not between", value1, value2, "otherInfo2");
            return (Criteria) this;
        }

        public Criteria andOtherInfo3IsNull() {
            addCriterion("OTHER_INFO3 is null");
            return (Criteria) this;
        }

        public Criteria andOtherInfo3IsNotNull() {
            addCriterion("OTHER_INFO3 is not null");
            return (Criteria) this;
        }

        public Criteria andOtherInfo3EqualTo(String value) {
            addCriterion("OTHER_INFO3 =", value, "otherInfo3");
            return (Criteria) this;
        }

        public Criteria andOtherInfo3NotEqualTo(String value) {
            addCriterion("OTHER_INFO3 <>", value, "otherInfo3");
            return (Criteria) this;
        }

        public Criteria andOtherInfo3GreaterThan(String value) {
            addCriterion("OTHER_INFO3 >", value, "otherInfo3");
            return (Criteria) this;
        }

        public Criteria andOtherInfo3GreaterThanOrEqualTo(String value) {
            addCriterion("OTHER_INFO3 >=", value, "otherInfo3");
            return (Criteria) this;
        }

        public Criteria andOtherInfo3LessThan(String value) {
            addCriterion("OTHER_INFO3 <", value, "otherInfo3");
            return (Criteria) this;
        }

        public Criteria andOtherInfo3LessThanOrEqualTo(String value) {
            addCriterion("OTHER_INFO3 <=", value, "otherInfo3");
            return (Criteria) this;
        }

        public Criteria andOtherInfo3Like(String value) {
            addCriterion("OTHER_INFO3 like", value, "otherInfo3");
            return (Criteria) this;
        }

        public Criteria andOtherInfo3NotLike(String value) {
            addCriterion("OTHER_INFO3 not like", value, "otherInfo3");
            return (Criteria) this;
        }

        public Criteria andOtherInfo3In(List<String> values) {
            addCriterion("OTHER_INFO3 in", values, "otherInfo3");
            return (Criteria) this;
        }

        public Criteria andOtherInfo3NotIn(List<String> values) {
            addCriterion("OTHER_INFO3 not in", values, "otherInfo3");
            return (Criteria) this;
        }

        public Criteria andOtherInfo3Between(String value1, String value2) {
            addCriterion("OTHER_INFO3 between", value1, value2, "otherInfo3");
            return (Criteria) this;
        }

        public Criteria andOtherInfo3NotBetween(String value1, String value2) {
            addCriterion("OTHER_INFO3 not between", value1, value2, "otherInfo3");
            return (Criteria) this;
        }

        public Criteria andOtherInfo4IsNull() {
            addCriterion("OTHER_INFO4 is null");
            return (Criteria) this;
        }

        public Criteria andOtherInfo4IsNotNull() {
            addCriterion("OTHER_INFO4 is not null");
            return (Criteria) this;
        }

        public Criteria andOtherInfo4EqualTo(String value) {
            addCriterion("OTHER_INFO4 =", value, "otherInfo4");
            return (Criteria) this;
        }

        public Criteria andOtherInfo4NotEqualTo(String value) {
            addCriterion("OTHER_INFO4 <>", value, "otherInfo4");
            return (Criteria) this;
        }

        public Criteria andOtherInfo4GreaterThan(String value) {
            addCriterion("OTHER_INFO4 >", value, "otherInfo4");
            return (Criteria) this;
        }

        public Criteria andOtherInfo4GreaterThanOrEqualTo(String value) {
            addCriterion("OTHER_INFO4 >=", value, "otherInfo4");
            return (Criteria) this;
        }

        public Criteria andOtherInfo4LessThan(String value) {
            addCriterion("OTHER_INFO4 <", value, "otherInfo4");
            return (Criteria) this;
        }

        public Criteria andOtherInfo4LessThanOrEqualTo(String value) {
            addCriterion("OTHER_INFO4 <=", value, "otherInfo4");
            return (Criteria) this;
        }

        public Criteria andOtherInfo4Like(String value) {
            addCriterion("OTHER_INFO4 like", value, "otherInfo4");
            return (Criteria) this;
        }

        public Criteria andOtherInfo4NotLike(String value) {
            addCriterion("OTHER_INFO4 not like", value, "otherInfo4");
            return (Criteria) this;
        }

        public Criteria andOtherInfo4In(List<String> values) {
            addCriterion("OTHER_INFO4 in", values, "otherInfo4");
            return (Criteria) this;
        }

        public Criteria andOtherInfo4NotIn(List<String> values) {
            addCriterion("OTHER_INFO4 not in", values, "otherInfo4");
            return (Criteria) this;
        }

        public Criteria andOtherInfo4Between(String value1, String value2) {
            addCriterion("OTHER_INFO4 between", value1, value2, "otherInfo4");
            return (Criteria) this;
        }

        public Criteria andOtherInfo4NotBetween(String value1, String value2) {
            addCriterion("OTHER_INFO4 not between", value1, value2, "otherInfo4");
            return (Criteria) this;
        }

        public Criteria andOtherInfo5IsNull() {
            addCriterion("OTHER_INFO5 is null");
            return (Criteria) this;
        }

        public Criteria andOtherInfo5IsNotNull() {
            addCriterion("OTHER_INFO5 is not null");
            return (Criteria) this;
        }

        public Criteria andOtherInfo5EqualTo(String value) {
            addCriterion("OTHER_INFO5 =", value, "otherInfo5");
            return (Criteria) this;
        }

        public Criteria andOtherInfo5NotEqualTo(String value) {
            addCriterion("OTHER_INFO5 <>", value, "otherInfo5");
            return (Criteria) this;
        }

        public Criteria andOtherInfo5GreaterThan(String value) {
            addCriterion("OTHER_INFO5 >", value, "otherInfo5");
            return (Criteria) this;
        }

        public Criteria andOtherInfo5GreaterThanOrEqualTo(String value) {
            addCriterion("OTHER_INFO5 >=", value, "otherInfo5");
            return (Criteria) this;
        }

        public Criteria andOtherInfo5LessThan(String value) {
            addCriterion("OTHER_INFO5 <", value, "otherInfo5");
            return (Criteria) this;
        }

        public Criteria andOtherInfo5LessThanOrEqualTo(String value) {
            addCriterion("OTHER_INFO5 <=", value, "otherInfo5");
            return (Criteria) this;
        }

        public Criteria andOtherInfo5Like(String value) {
            addCriterion("OTHER_INFO5 like", value, "otherInfo5");
            return (Criteria) this;
        }

        public Criteria andOtherInfo5NotLike(String value) {
            addCriterion("OTHER_INFO5 not like", value, "otherInfo5");
            return (Criteria) this;
        }

        public Criteria andOtherInfo5In(List<String> values) {
            addCriterion("OTHER_INFO5 in", values, "otherInfo5");
            return (Criteria) this;
        }

        public Criteria andOtherInfo5NotIn(List<String> values) {
            addCriterion("OTHER_INFO5 not in", values, "otherInfo5");
            return (Criteria) this;
        }

        public Criteria andOtherInfo5Between(String value1, String value2) {
            addCriterion("OTHER_INFO5 between", value1, value2, "otherInfo5");
            return (Criteria) this;
        }

        public Criteria andOtherInfo5NotBetween(String value1, String value2) {
            addCriterion("OTHER_INFO5 not between", value1, value2, "otherInfo5");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateUidIsNull() {
            addCriterion("CREATE_UID is null");
            return (Criteria) this;
        }

        public Criteria andCreateUidIsNotNull() {
            addCriterion("CREATE_UID is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUidEqualTo(String value) {
            addCriterion("CREATE_UID =", value, "createUid");
            return (Criteria) this;
        }

        public Criteria andCreateUidNotEqualTo(String value) {
            addCriterion("CREATE_UID <>", value, "createUid");
            return (Criteria) this;
        }

        public Criteria andCreateUidGreaterThan(String value) {
            addCriterion("CREATE_UID >", value, "createUid");
            return (Criteria) this;
        }

        public Criteria andCreateUidGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_UID >=", value, "createUid");
            return (Criteria) this;
        }

        public Criteria andCreateUidLessThan(String value) {
            addCriterion("CREATE_UID <", value, "createUid");
            return (Criteria) this;
        }

        public Criteria andCreateUidLessThanOrEqualTo(String value) {
            addCriterion("CREATE_UID <=", value, "createUid");
            return (Criteria) this;
        }

        public Criteria andCreateUidLike(String value) {
            addCriterion("CREATE_UID like", value, "createUid");
            return (Criteria) this;
        }

        public Criteria andCreateUidNotLike(String value) {
            addCriterion("CREATE_UID not like", value, "createUid");
            return (Criteria) this;
        }

        public Criteria andCreateUidIn(List<String> values) {
            addCriterion("CREATE_UID in", values, "createUid");
            return (Criteria) this;
        }

        public Criteria andCreateUidNotIn(List<String> values) {
            addCriterion("CREATE_UID not in", values, "createUid");
            return (Criteria) this;
        }

        public Criteria andCreateUidBetween(String value1, String value2) {
            addCriterion("CREATE_UID between", value1, value2, "createUid");
            return (Criteria) this;
        }

        public Criteria andCreateUidNotBetween(String value1, String value2) {
            addCriterion("CREATE_UID not between", value1, value2, "createUid");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateUidIsNull() {
            addCriterion("UPDATE_UID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUidIsNotNull() {
            addCriterion("UPDATE_UID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUidEqualTo(String value) {
            addCriterion("UPDATE_UID =", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidNotEqualTo(String value) {
            addCriterion("UPDATE_UID <>", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidGreaterThan(String value) {
            addCriterion("UPDATE_UID >", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_UID >=", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidLessThan(String value) {
            addCriterion("UPDATE_UID <", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_UID <=", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidLike(String value) {
            addCriterion("UPDATE_UID like", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidNotLike(String value) {
            addCriterion("UPDATE_UID not like", value, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidIn(List<String> values) {
            addCriterion("UPDATE_UID in", values, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidNotIn(List<String> values) {
            addCriterion("UPDATE_UID not in", values, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidBetween(String value1, String value2) {
            addCriterion("UPDATE_UID between", value1, value2, "updateUid");
            return (Criteria) this;
        }

        public Criteria andUpdateUidNotBetween(String value1, String value2) {
            addCriterion("UPDATE_UID not between", value1, value2, "updateUid");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("DEL_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("DEL_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(Integer value) {
            addCriterion("DEL_FLAG =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(Integer value) {
            addCriterion("DEL_FLAG <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(Integer value) {
            addCriterion("DEL_FLAG >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("DEL_FLAG >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(Integer value) {
            addCriterion("DEL_FLAG <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(Integer value) {
            addCriterion("DEL_FLAG <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<Integer> values) {
            addCriterion("DEL_FLAG in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<Integer> values) {
            addCriterion("DEL_FLAG not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(Integer value1, Integer value2) {
            addCriterion("DEL_FLAG between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("DEL_FLAG not between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andUserRolesInSysIsNull() {
            addCriterion("USER_ROLES_IN_SYS is null");
            return (Criteria) this;
        }

        public Criteria andUserRolesInSysIsNotNull() {
            addCriterion("USER_ROLES_IN_SYS is not null");
            return (Criteria) this;
        }

        public Criteria andUserRolesInSysEqualTo(String value) {
            addCriterion("USER_ROLES_IN_SYS =", value, "userRolesInSys");
            return (Criteria) this;
        }

        public Criteria andUserRolesInSysNotEqualTo(String value) {
            addCriterion("USER_ROLES_IN_SYS <>", value, "userRolesInSys");
            return (Criteria) this;
        }

        public Criteria andUserRolesInSysGreaterThan(String value) {
            addCriterion("USER_ROLES_IN_SYS >", value, "userRolesInSys");
            return (Criteria) this;
        }

        public Criteria andUserRolesInSysGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ROLES_IN_SYS >=", value, "userRolesInSys");
            return (Criteria) this;
        }

        public Criteria andUserRolesInSysLessThan(String value) {
            addCriterion("USER_ROLES_IN_SYS <", value, "userRolesInSys");
            return (Criteria) this;
        }

        public Criteria andUserRolesInSysLessThanOrEqualTo(String value) {
            addCriterion("USER_ROLES_IN_SYS <=", value, "userRolesInSys");
            return (Criteria) this;
        }

        public Criteria andUserRolesInSysLike(String value) {
            addCriterion("USER_ROLES_IN_SYS like", value, "userRolesInSys");
            return (Criteria) this;
        }

        public Criteria andUserRolesInSysNotLike(String value) {
            addCriterion("USER_ROLES_IN_SYS not like", value, "userRolesInSys");
            return (Criteria) this;
        }

        public Criteria andUserRolesInSysIn(List<String> values) {
            addCriterion("USER_ROLES_IN_SYS in", values, "userRolesInSys");
            return (Criteria) this;
        }

        public Criteria andUserRolesInSysNotIn(List<String> values) {
            addCriterion("USER_ROLES_IN_SYS not in", values, "userRolesInSys");
            return (Criteria) this;
        }

        public Criteria andUserRolesInSysBetween(String value1, String value2) {
            addCriterion("USER_ROLES_IN_SYS between", value1, value2, "userRolesInSys");
            return (Criteria) this;
        }

        public Criteria andUserRolesInSysNotBetween(String value1, String value2) {
            addCriterion("USER_ROLES_IN_SYS not between", value1, value2, "userRolesInSys");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table USER_INFO
     *
     * @mbg.generated do_not_delete_during_merge Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table USER_INFO
     *
     * @mbg.generated Tue Jan 21 13:16:13 GMT+08:00 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}